### ISSUE TITLE
sudo: you do not exist in the passwd database

### ISSUE THREAD

**Issue by ondras12345** [jojo141185/mopidy-docker#30]
When trying to run as a non-root user:
```
services:
  mopidy:
    image: 'jojo141185/mopidy:develop'
    container_name: mopidy
    restart: unless-stopped
    user: 999:991
    group_add:
      - audio
 
    devices:
      - /dev/snd
 
    volumes:
      - './config:/config'
      - './local:/var/lib/mopidy/.local'
      - './cache:/var/lib/mopidy/.cache'
 
    ports:
      # Mopidy-MPD
      - "6600:6600"
      # Mopidy-HTTP
      - "127.0.0.1:6680:6680"
```

I get
```
$ docker compose logs -f
mopidy  | sudo: you do not exist in the passwd database
mopidy  | sudo: you do not exist in the passwd database
[...]
```

This same config was working with `test_release` and versions prior to that.

I tried removing `user: 999:991` to let it run as root, but then I got this instead:
```
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
```
That might be because this command
https://github.com/jojo141185/mopidy-docker/blob/3f25945c3a95c226faa67a693c1451a240bb276f/Dockerfile#L245
does not set `u+x` on /entrypoint.sh.

**Comment by jojo141185** [comment]
I think the error you're seeing (sudo: you do not exist in the passwd database) occurs because the container is not being started as root, which is necessary for the entrypoint script to modify the user and group IDs (UID/GID) based on the PUID and PGID environment variables.

Possible solution:

1. Start the Container as Root: The container needs to be run as root in order to adjust the user (mopidy) and group (audio) IDs. Ensure there is no user field specified in your docker-compose.yml file, or explicitly run the container as root. The entrypoint script will handle the UID/GID modification if it's running with the required permissions.
2. Set PUID and PGID in docker-compose.yml: Make sure that the PUID and PGID environment variables are set in your docker-compose.yml file to match the correct user and group IDs on your host system. 

Once you start the container as root with the correct PUID and PGID environment variables, this issue should be resolved.

Let me know if the problem persists after trying these steps!

**Comment by ondras12345** [comment]
Hi, thanks for looking into it.
I'm pretty sure I already tested this, but I'll try again:

```console
$ cat compose.yml
services:
  mopidy:
    image: 'jojo141185/mopidy:develop'
    container_name: mopidy
    restart: unless-stopped
    devices:
      - /dev/snd
    volumes:
      - './config:/config'
      - '/media/NAS-media:/NAS-media:ro'
      # Store mopidy library and images on host (persistent)
      # was local, changed to .local
      - './local:/var/lib/mopidy/.local'
      # Spotify cache
      - './cache:/var/lib/mopidy/.cache'
    ports:
      # Mopidy-MPD
      - "6600:6600"
      # Mopidy-HTTP
      - "127.0.0.1:6680:6680"
    environment:
      - PUID=999
      - PGID=991


$ id homeassistant 
uid=999(homeassistant) gid=991(homeassistant) groups=991(homeassistant),20(dialout),29(audio),44(video),993(gpio),992(docker)

$ sudo -u homeassistant docker compose pull
[...]

$ sudo -u homeassistant docker compose down
[+] Running 2/2
 ✔ Container mopidy        Removed
 ✔ Network mopidy_default  Removed

$ sudo -u homeassistant docker compose up 
[+] Running 2/2
 ✔ Network mopidy_default  Created                                                                                                    0.2s 
 ✔ Container mopidy        Created                                                                                                    0.3s 
Attaching to mopidy
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy exited with code 0
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy  | [dumb-init] /entrypoint.sh: Permission denied
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/0
 ✔ Container mopidy  Stopped                                                                                                          0.0s 
canceled

$
```

**Comment by ondras12345** [comment]
I tried fixing the permissions of `/entrypoint.sh`, but it still doesn't work:
```console
$ cat compose.yml
services:
  mopidy:
    build:
      context: testing
    container_name: mopidy
    restart: unless-stopped

    devices:
      - /dev/snd

    volumes:
      - './config:/config'
      # Store mopidy library and images on host (persistent)
      # was local, changed to .local
      - './local:/var/lib/mopidy/.local'
      # Spotify cache
      - './cache:/var/lib/mopidy/.cache'

    ports:
      # Mopidy-MPD
      - "6600:6600"
      # Mopidy-HTTP
      - "127.0.0.1:6680:6680"

    environment:
      - PUID=999
      - PGID=991

$ cat testing/Dockerfile
FROM jojo141185/mopidy:develop

RUN chmod u+x /entrypoint.sh
$ sudo -u homeassistant docker compose build
[...]
$ sudo -u homeassistant docker compose up
[+] Running 1/1
 ✔ Container mopidy  Recreated                                                                                                        0.3s 
Attaching to mopidy
mopidy  | Requested change of UID: 999 and GID: 991 for running user.
mopidy  | Changing mopidy user to UID 999
mopidy  | usermod: user mopidy is currently used by process 1
mopidy  | id: 'audio': no such user
mopidy  | /entrypoint.sh: line 34: [: -eq: unary operator expected
mopidy  | Changing audio group to GID 991
mopidy  | groupmod: Permission denied.
mopidy  | groupmod: cannot lock /etc/group; try again later.
[...]
mopidy  | Sorry, user mopidy is not allowed to execute '/usr/local/bin/mopidy' as mopidy on 48d4cca2ff04.
mopidy exited with code 0
```

**Comment by jojo141185** [comment]
Meanwhile I'm back home, but I can't reproduce your problem on my side. 
Can you make sure that the container is running by root?

docker-compose.yml
```
version: '3.5'
services:
  mopidy:
    container_name: mopidy
    image: 'jojo141185/mopidy:develop'
    restart: unless-stopped

    ## Run container as root (this is required to modify the PUID and PGID by entrypoint script)
    user: root

    ## Add container to audio group 
    # change group name or id to your system's audio group
    group_add:
        - audio
        
    ## Add audio device 
    # change to your system's audio device (see Readme)
    devices:
      - /dev/snd

    volumes:
      # Mopidy config files
      - './config:/config'
      # Store mopidy library and images on host (persistent)
      - './local:/var/lib/mopidy/local'
      # Spotify credential cache
      - './.spotify:/var/lib/mopidy/spotify'

    ports:
      # Mopidy-MPD
      - "6600:6600"
      # Mopidy-HTTP
      - "6680:6680"

    environment:
      # Select specific privileged user / group to run the mopidy process
      - PUID=999
      - PGID=991
```

Start the container
$ sudo docker compose up
